"""initial schema

Revision ID: 3bdcce288120
Revises: 
Create Date: 2026-06-17 12:02:40.763816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3bdcce288120'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('scale_min', sa.Integer(), nullable=True),
    sa.Column('scale_max', sa.Integer(), nullable=True),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('is_subjective', sa.Boolean(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteria_id'), ['id'], unique=False)

    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('county', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Float(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_archived'), ['archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_baths'), ['baths'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_beds'), ['beds'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_latitude'), ['latitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_longitude'), ['longitude'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_property_type'), ['property_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_properties_zip'), ['zip'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tags_name'), ['name'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('criterion_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('criterion_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criterion_id'], ['criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'criterion_id', 'user_id', name='uq_criterion_value')
    )
    with op.batch_alter_table('criterion_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criterion_values_criterion_id'), ['criterion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_values_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criterion_values_property_id'), ['property_id'], unique=False)

    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('origin', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_property_id'), ['property_id'], unique=False)

    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notes_property_id'), ['property_id'], unique=False)

    op.create_table('place_distances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('place_name', sa.String(), nullable=True),
    sa.Column('place_address', sa.String(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('place_distances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_place_distances_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_distances_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_place_distances_property_id'), ['property_id'], unique=False)

    op.create_table('points_of_interest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('points_of_interest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_points_of_interest_id'), ['id'], unique=False)

    op.create_table('property_tags',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'tag_id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_history_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_history_property_id'), ['property_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_history_property_id'))
        batch_op.drop_index(batch_op.f('ix_status_history_id'))

    op.drop_table('status_history')
    op.drop_table('property_tags')
    with op.batch_alter_table('points_of_interest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_points_of_interest_id'))

    op.drop_table('points_of_interest')
    with op.batch_alter_table('place_distances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_place_distances_property_id'))
        batch_op.drop_index(batch_op.f('ix_place_distances_id'))
        batch_op.drop_index(batch_op.f('ix_place_distances_category'))

    op.drop_table('place_distances')
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_property_id'))
        batch_op.drop_index(batch_op.f('ix_notes_id'))

    op.drop_table('notes')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_property_id'))
        batch_op.drop_index(batch_op.f('ix_media_id'))

    op.drop_table('media')
    with op.batch_alter_table('criterion_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criterion_values_property_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_values_id'))
        batch_op.drop_index(batch_op.f('ix_criterion_values_criterion_id'))

    op.drop_table('criterion_values')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_name'))
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_zip'))
        batch_op.drop_index(batch_op.f('ix_properties_status'))
        batch_op.drop_index(batch_op.f('ix_properties_state'))
        batch_op.drop_index(batch_op.f('ix_properties_source_id'))
        batch_op.drop_index(batch_op.f('ix_properties_property_type'))
        batch_op.drop_index(batch_op.f('ix_properties_price'))
        batch_op.drop_index(batch_op.f('ix_properties_longitude'))
        batch_op.drop_index(batch_op.f('ix_properties_latitude'))
        batch_op.drop_index(batch_op.f('ix_properties_id'))
        batch_op.drop_index(batch_op.f('ix_properties_city'))
        batch_op.drop_index(batch_op.f('ix_properties_beds'))
        batch_op.drop_index(batch_op.f('ix_properties_baths'))
        batch_op.drop_index(batch_op.f('ix_properties_archived'))

    op.drop_table('properties')
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteria_id'))

    op.drop_table('criteria')
    # ### end Alembic commands ###
